# Generated by Django 3.2.4 on 2021-06-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw', '0005_auto_20210619_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
