# Generated by Django 3.2.4 on 2021-06-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw', '0008_auto_20210621_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
