# Generated by Django 3.2.4 on 2021-08-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw', '0011_alter_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
    ]
